site_name: CoderDojo - Friedrichshain
pages:
    - 'Übersicht': index.md
    - 'Blockbasierte Sprachen': block_based.md
    - 'Python': python.md
theme: readthedocs
use_directory_urls: false
strict: true
markdown_extensions:
    - markdown.extensions.toc
    - markdown.extensions.abbr
    - markdown.extensions.fenced_code
    - markdown.extensions.def_list
    - markdown.extensions.footnotes
    - markdown.extensions.tables
    - markdown.extensions.codehilite
    - markdown.extensions.sane_lists
    - markdown.extensions.wikilinks
